# Generated by Django 3.2 on 2021-09-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.PositiveIntegerField(choices=[('Python', 'Python'), ('Framework Django', 'Framework Django'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS'), ('React', 'React'), ('Figma', 'Figma'), ('Photoshop', 'Photoshop')], default='Python')),
                ('start', models.DateField(blank=True, null=True)),
                ('finish', models.DateField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(choices=[('No', 'No'), ('FULL', 'FULL'), ('PART', 'PART')], default='No')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=90)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('spec', models.CharField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design')], default='Spec_Choices', max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='fullname')),
                ('age', models.PositiveIntegerField(verbose_name='age')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('payment', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='No', max_length=5)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('11:30 - 13:00', '11:30 - 13:00'), ('14:00 - 15:30', '14:00 - 15:30'), ('15:30 - 17:00', '15:30 - 17:00'), ('17:00 - 18:30', '17:00 - 18:30'), ('18:30 - 20:00', '18:30 - 20:00')], default='11:30 - 13:00', max_length=13)),
                ('room', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Co-working', 'Co-working')], default='First', max_length=50)),
                ('student_qty', models.PositiveIntegerField()),
                ('total', models.CharField(max_length=90)),
                ('status', models.CharField(choices=[('No', 'No'), ('FULL', 'FULL'), ('PART', 'PART')], default='Planned', max_length=8)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.courses')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapp.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('specification', models.CharField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design')], default='WEB DEVELOPMENT', max_length=45)),
                ('developer_tech', models.CharField(choices=[('Python', 'Python'), ('Framework Django', 'Framework Django'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS'), ('React', 'React'), ('Figma', 'Figma'), ('Photoshop', 'Photoshop')], default='FRONTEND', max_length=25)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.mentor')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.mentor'),
        ),
    ]
