# Generated by Django 3.2 on 2021-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='developer_tech',
            field=models.CharField(choices=[('Python', 'Python'), ('Framework Django', 'Framework Django'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS'), ('React', 'React'), ('Figma', 'Figma'), ('Photoshop', 'Photoshop')], default='Front end', max_length=25),
        ),
        migrations.AlterField(
            model_name='group',
            name='specification',
            field=models.CharField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design')], default='Back end', max_length=45),
        ),
    ]
