# Generated by Django 3.2 on 2021-09-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_auto_20210921_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmapp.group'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='mentor',
            field=models.CharField(blank=True, choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='developer_tech',
            field=models.CharField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design')], default='Front end', max_length=14),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='group',
            name='specification',
            field=models.CharField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design')], default='Back end', max_length=23),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Framework Django', 'Framework Django'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS'), ('React', 'React'), ('Figma', 'Figma'), ('Photoshop', 'Photoshop')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='No', max_length=50),
        ),
    ]
