# Generated by Django 3.2 on 2021-09-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_auto_20210921_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='mentor',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
