# Generated by Django 3.2 on 2021-09-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_alter_courses_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='spec',
            field=models.PositiveIntegerField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design')], default='Python'),
        ),
    ]
