# Generated by Django 3.2 on 2021-09-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_alter_courses_spec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
