# Generated by Django 3.2 on 2021-09-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_delete_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Framework Django', 'Framework Django'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS'), ('React', 'React'), ('Figma', 'Figma'), ('Photoshop', 'Photoshop')], default='Python', max_length=50, null=True),
        ),
    ]
