# Generated by Django 3.2 on 2021-09-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0007_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='room',
            field=models.CharField(choices=[('First room', 'First room'), ('Second room', 'Second room'), ('Third room', 'Third room'), ('Co-working', 'Co-working')], default='First', max_length=50),
        ),
    ]
