# Generated by Django 3.2 on 2021-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_alter_lesson_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='spec',
            field=models.PositiveIntegerField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design'), ('SMM', 'SMM')], default='Python'),
        ),
        migrations.AlterField(
            model_name='group',
            name='developer_tech',
            field=models.CharField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design'), ('SMM', 'SMM')], default='Front end', max_length=14),
        ),
        migrations.AlterField(
            model_name='group',
            name='specification',
            field=models.CharField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design'), ('SMM', 'SMM')], default='Back end', max_length=23),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='spec',
            field=models.CharField(choices=[('Back end', 'Back end'), ('Front end', 'Front end'), ('Web design', 'Web design'), ('SMM', 'SMM')], default='Spec_Choices', max_length=90),
        ),
    ]
