# Generated by Django 3.2 on 2021-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_auto_20210922_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
