# Generated by Django 3.2 on 2021-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
