# Generated by Django 3.2 on 2021-09-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='developer_tech',
            field=models.CharField(choices=[('Python', 'Python'), ('Framework Django', 'Framework Django'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS'), ('React', 'React'), ('Figma', 'Figma'), ('Photoshop', 'Photoshop')], default='Front end', max_length=30),
        ),
    ]
